- name: Pull registry.fedoraproject.org/fedora-toolbox:33
  command: podman pull registry.fedoraproject.org/fedora-toolbox:33
  register: _podman
  until: _podman.rc == 0
  retries: 5
  delay: 10

- name: Pull registry.fedoraproject.org/fedora-toolbox:29
  command: podman pull registry.fedoraproject.org/fedora-toolbox:29
  register: _podman
  until: _podman.rc == 0
  retries: 5
  delay: 10
