---
- hosts: all
  tasks:
    - name: Install requirements
      become: yes
      package:
        use: dnf
        name:
          - flatpak-session-helper
          - systemd
          - bats
          - udisks2
          - podman
          - golang

    - name: Setup environment (create missing /run/media)
      command: sudo systemd-tmpfiles --create

    - name: Check versions of crucial packages
      command: rpm -q podman crun conmon fuse-overlayfs flatpak-session-helper golang

    - include_tasks: ./pre-common.yaml
