---
- hosts: ci-node-rawhide
  tasks:
    - name: Build toolbox
      command: go build
      args:
        chdir: '{{ zuul.project.src_dir }}'

    - name: Show the content of the source folder
      command: ls
      args:
        chdir: '{{ zuul.project.src_dir }}'

    - name: "Show PATH"
      debug:
        msg: The PATH is {{ ansible_env.PATH }}
      environment:
        PATH: '{{ zuul.project.src_dir }}/:{{ ansible_env.PATH }}'

    - name: Run system tests
      command: bats ./test/system
      environment:
        PODMAN: '/usr/bin/podman'
        PATH: '{{ zuul.project.src_dir }}/:{{ ansible_env.PATH }}'
      args:
        chdir: '{{ zuul.project.src_dir }}'
