---
- hosts: ci-node-rawhide
  tasks:
    - name: Build toolbox
      command: go build
      args:
        chdir: '{{ zuul.project.src_dir }}'

    - name: Show the content of the source folder
      command: ls
      args:
        chdir: '{{ zuul.project.src_dir }}'

    - name: Run system tests
      command: bats ./test/system
      environment:
        PODMAN: '/usr/bin/podman'
        TOOLBOX: './toolbox'
      args:
        chdir: '{{ zuul.project.src_dir }}'
